version: '2'
services:
  mysql:
    container_name: "budget-envelopes-mysql"
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=budget-envelopes
      - MYSQL_USER=budget-envelopes
      - MYSQL_PASSWORD=budget-envelopes
      - MYSQL_DATABASE=budget-envelopes
    volumes:
      - './docker/data/mysql:/var/lib/mysql'
    ports:
      - "33060:3306"
